language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sooyouz/docker-react .

script:
  - docker run -e CI=true sooyouz/docker-react npm run test